services:
  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: spring_ajay
      DB_USERNAME: root
      DB_PASSWORD: ""
  database:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: spring_ajay
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
